[package]
name = "search_pronoun"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
clap = "2.33.3"
docx-rs = "0.2"
serde_json = "1.0.58"
